### ISSUE TITLE
has gulp-util dependency but no that plugin after installation

### ISSUE THREAD

**Issue by riotkkwok** [Forumouth/gulp-scss#15]
Error: Cannot find module 'gulp-util'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\SVN\dev\trunk\src\3g\mobile-prototype\testGulp2\no
de_modules\gulp-scss\lib\scss.js:8:11)
    at Object.<anonymous> (D:\SVN\dev\trunk\src\3g\mobile-prototype\testGulp2\no
de_modules\gulp-scss\lib\scss.js:93:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

BTW, I'm so disappointed that this plugin does not support compass.

**Comment by hiroaki-yamamoto** [comment]
Seems to be my mistake... again.

I will fix it, but please add `gulp-util` manually until the new update is available.
Thanks.
