### ISSUE TITLE
Error : ENOENT, no such file or directory

### ISSUE THREAD

**Issue by mbaumanndev** [Forumouth/gulp-scss#19]
Hello,

I'm trying to run a task using gulp-scss, but it fails with this error :

```
[00:03:52] Using gulpfile D:\Documents\GitHub\maxslayer44.github.io\Gulpfile.js
[00:03:52] Starting 'styles'...
scss Compilation failed.: Error: ENOENT, no such file or directory 'D:\Documents\GitHub\maxslayer44.github.io\.gulp-scss-cache\_ressources\styles\style.css'
Stack Trace:
Error: ENOENT, no such file or directory 'D:\Documents\GitHub\maxslayer44.github.io\.gulp-scss-cache\_ressources\styles\style.css'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at D:\Documents\GitHub\maxslayer44.github.io\node_modules\gulp-scss\lib\scss.js:59:27
    at _fulfilled (D:\Documents\GitHub\maxslayer44.github.io\node_modules\gulp-scss\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (D:\Documents\GitHub\maxslayer44.github.io\node_modules\gulp-scss\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (D:\Documents\GitHub\maxslayer44.github.io\node_modules\gulp-scss\node_modules\q\q.js:796:13)
    at D:\Documents\GitHub\maxslayer44.github.io\node_modules\gulp-scss\node_modules\q\q.js:604:44
    at runSingle (D:\Documents\GitHub\maxslayer44.github.io\node_modules\gulp-scss\node_modules\q\q.js:137:13)
    at flush (D:\Documents\GitHub\maxslayer44.github.io\node_modules\gulp-scss\node_modules\q\q.js:125:13)
```

This is my Gulpfile.js

``` javascript
var gulp = require("gulp");
var util = require("gulp-util");

var concat = require("gulp-concat");
var uglify = require("gulp-uglify");
var header = require("gulp-header");
var scss = require("gulp-scss");
var autoprefixer = require('gulp-autoprefixer');
var minifyCss = require('gulp-minify-css');
var rename = require('gulp-rename');
var del = require('del');

var newer = require('gulp-newer');
var changed = require('gulp-changed');

var pkg = require("./package.json");
var currentYear = util.date(new Date(), "yyyy");

var paths = {
    scripts: [
        "./_ressources/scripts/utils.js",
        "./_ressources/scripts/main.js"
    ],
    styles: [
        "./_ressources/styles/style.scss"
    ],
    statics: [
        "./_ressources/statics/**/*"
    ],
    build: "./public"
}

var bannerScript = [
    "/*!",
    " * <%= pkg.name %> v<%= pkg.version %> | Copyright (c) 2012-<%= currentYear %> <%= pkg.author %> | <%= pkg.homepage %>",
    " */",
    ""
].join('\n');

var bannerStyle = [
    "/*!",
    " * <%= pkg.name %> v<%= pkg.version %> | Copyright (c) 2012-<%= currentYear %> <%= pkg.author %> | <%= pkg.homepage %>",
    " * normalize.css v3.0.2 | MIT License | git.io/normalize",
    " * animate.scss v3.2.0 | MIT License | github.com/geoffgraham/animate.scss",
    " */",
    ""
].join('\n');

gulp.task("scripts", function() {
    return gulp.src(paths.scripts)
        .pipe(concat("site.min.js"))
        .pipe(uglify())
        .pipe(header(bannerScript, {pkg: pkg, currentYear: currentYear}))
        .pipe(gulp.dest(paths.build));
});

// Here
gulp.task("styles", function() {
    return gulp.src(paths.styles)
        .on('error', function(err){ console.log("src " + err.message); })
        .pipe(scss()) // Fails here
        .on('error', function(err){ console.log("scss " + err.message); })
        .pipe(autoprefixer())
        .on('error', function(err){ console.log("autoprefixer " + err.message); })
        .pipe(minifyCss({keepSpecialComments: 0}))
        .on('error', function(err){ console.log("minify " + err.message); })
        .pipe(header(bannerStyle, {pkg: pkg, currentYear: currentYear}))
        .on('error', function(err){ console.log("banner " + err.message); })
        .pipe(rename({suffix: ".min"}))
        .on('error', function(err){ console.log("rename " + err.message); })
        .pipe(gulp.dest(paths.build))
        .on('error', function(err){ console.log("dest " + err.message); });
});

gulp.task("statics", function() {
    return gulp.src(paths.statics)
        .pipe(newer(paths.build))
        .pipe(changed(paths.build))
        .pipe(gulp.dest(paths.build))
});

gulp.task("clean", function() {
    return gulp.pipe(del([paths.build + "/*"]));
});

gulp.task("watch", function() {
    gulp.watch(paths.scripts, ["scripts"]);
    gulp.watch(paths.styles, ["styles"]);
    gulp.watch(paths.statics, ["statics"]);
});

gulp.task("default", ["scripts", "styles", "statics"]);
```

Gulp fails when it's trying to use the scss task, searching for a file wich doesn't exists, if I create this file manually, it copy its content in the destination file, but it never compiles the scss files.

**Comment by hiroaki-yamamoto** [comment]
Couldn't confirm the problem....
